version: '2'
services:
  web:
    image: php:apache
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - pozos
  api:
    image: api-pozos:v1
    ports:
      - "8081:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - pozos
      
      
networks:
  pozos:
